name: modular_foundation_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.3

# Add regular dependencies here.
dependencies:
  custom_lint_builder: ^0.8.1
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
